#!/bin/sh -e

export CFLAGS="   \
-ansi             \
-g                \
-Og               \
-pedantic         \
-pedantic-errors  \
-Wall             \
-Werror           \
-Wextra           \
"

exec ./configure $@
